In [1]:
import pandas as pd

In [11]:
cereal = pd.read_csv ('cereal.csv')

In [3]:
#cereal.sort_index(inplace = True)

In [12]:
cereal

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6,280,25,3,1.0,0.33,68.402973
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8,135,0,3,1.0,1.00,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5,320,25,3,1.0,0.33,59.425505
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0,330,25,3,1.0,0.50,93.704912
4,Almond Delight,R,C,110,2,2,200,1.0,14.0,8,-1,25,3,1.0,0.75,34.384843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,Triples,G,C,110,2,1,250,0.0,21.0,3,60,25,3,1.0,0.75,39.106174
73,Trix,G,C,110,1,1,140,0.0,13.0,12,25,25,2,1.0,1.00,27.753301
74,Wheat Chex,R,C,100,3,1,230,3.0,17.0,3,115,25,1,1.0,0.67,49.787445
75,Wheaties,G,C,100,3,1,200,3.0,17.0,3,110,25,1,1.0,1.00,51.592193
76,Wheaties Honey Gold,G,C,110,2,1,200,1.0,16.0,8,60,25,1,1.0,0.75,36.187559

In [13]:
mfrg = cereal.groupby('mfr')

In [9]:
mfrg['fat'].mean()

mfr
A    1.000000
G    1.363636
K    0.608696
N    0.166667
P    0.888889
Q    1.750000
R    1.250000
Name: fat, dtype: float64

In [7]:
mfrg.info()

AttributeError: 'DataFrameGroupBy' object has no attribute 'info'

In [8]:
type(mfrg)

pandas.core.groupby.generic.DataFrameGroupBy

In [14]:
mfrg.first()

,name,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
mfr,,,,,,,,,,,,,,,
A,Maypo,H,100,4,1,0,0.0,16.0,3,95,25,2,1.0,1.00,54.850917
G,Apple Cinnamon Cheerios,C,110,2,2,180,1.5,10.5,10,70,25,1,1.0,0.75,29.509541
K,All-Bran,C,70,4,1,260,9.0,7.0,5,320,25,3,1.0,0.33,59.425505
N,100% Bran,C,70,4,1,130,10.0,5.0,6,280,25,3,1.0,0.33,68.402973
P,Bran Flakes,C,90,3,0,210,5.0,13.0,5,190,25,3,1.0,0.67,53.313813
Q,100% Natural Bran,C,120,3,5,15,2.0,8.0,8,135,0,3,1.0,1.00,33.983679
R,Almond Delight,C,110,2,2,200,1.0,14.0,8,-1,25,3,1.0,0.75,34.384843

In [16]:
mfrg.last()

,name,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
mfr,,,,,,,,,,,,,,,
A,Maypo,H,100,4,1,0,0.0,16.0,3,95,25,2,1.00,1.00,54.850917
G,Wheaties Honey Gold,C,110,2,1,200,1.0,16.0,8,60,25,1,1.00,0.75,36.187559
K,Special K,C,110,6,0,230,1.0,16.0,3,55,25,1,1.00,1.00,53.131324
N,Strawberry Fruit Wheats,C,90,2,0,15,3.0,15.0,5,90,25,2,1.00,1.00,59.363993
P,Post Nat. Raisin Bran,C,120,3,1,200,6.0,11.0,14,260,25,3,1.33,0.67,37.840594
Q,Quaker Oatmeal,H,100,5,2,0,2.7,-1.0,-1,110,0,1,1.00,0.67,50.828392
R,Wheat Chex,C,100,3,1,230,3.0,17.0,3,115,25,1,1.00,0.67,49.787445

In [17]:
cereal.tail()

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
72,Triples,G,C,110,2,1,250,0.0,21.0,3,60,25,3,1.0,0.75,39.106174
73,Trix,G,C,110,1,1,140,0.0,13.0,12,25,25,2,1.0,1.00,27.753301
74,Wheat Chex,R,C,100,3,1,230,3.0,17.0,3,115,25,1,1.0,0.67,49.787445
75,Wheaties,G,C,100,3,1,200,3.0,17.0,3,110,25,1,1.0,1.00,51.592193
76,Wheaties Honey Gold,G,C,110,2,1,200,1.0,16.0,8,60,25,1,1.0,0.75,36.187559

In [18]:
mfrg['calories'].last()

mfr
A    100
G    110
K    110
N     90
P    120
Q    100
R    100
Name: calories, dtype: int64

In [19]:
mfrg.mean()

,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
mfr,,,,,,,,,,,,,
A,100.000000,4.000000,1.000000,0.000000,0.000000,16.000000,3.000000,95.000000,25.000000,2.000000,1.000000,1.000000,54.850917
G,111.363636,2.318182,1.363636,200.454545,1.272727,14.727273,7.954545,85.227273,35.227273,2.136364,1.049091,0.875000,34.485852
K,108.695652,2.652174,0.608696,174.782609,2.739130,15.130435,7.565217,103.043478,34.782609,2.347826,1.077826,0.796087,44.038462
N,86.666667,2.833333,0.166667,37.500000,4.000000,16.000000,1.833333,120.666667,8.333333,1.666667,0.971667,0.778333,67.968567
P,108.888889,2.444444,0.888889,146.111111,2.777778,13.222222,8.777778,113.888889,25.000000,2.444444,1.064444,0.714444,41.705744
Q,95.000000,2.625000,1.750000,92.500000,1.337500,10.000000,5.250000,74.375000,12.500000,2.375000,0.875000,0.823750,42.915990
R,115.000000,2.500000,1.250000,198.125000,1.875000,17.625000,6.125000,89.250000,25.000000,2.000000,1.000000,0.871250,41.542997

In [21]:
mfrg.describe()

    calories                                                            \
       count        mean        std    min    25%    50%    75%    max
mfr
A        1.0  100.000000        NaN  100.0  100.0  100.0  100.0  100.0
G       22.0  111.363636  10.371873  100.0  110.0  110.0  110.0  140.0
K       23.0  108.695652  22.218818   50.0  100.0  110.0  115.0  160.0
N        6.0   86.666667  10.327956   70.0   82.5   90.0   90.0  100.0
P        9.0  108.888889  10.540926   90.0  100.0  110.0  120.0  120.0
Q        8.0   95.000000  29.277002   50.0   87.5  100.0  120.0  120.0
R        8.0  115.000000  22.677868   90.0  100.0  110.0  120.0  150.0

    protein            ...  cups       rating                        \
      count      mean  ...   75%   max  count       mean        std
mfr                    ...
A       1.0  4.000000  ...  1.00  1.00    1.0  54.850917        NaN
G      22.0  2.318182  ...  1.00  1.50   22.0  34.485852   8.946704
K      23.0  2.652174  ...  1.00  1.00   23.0  44.038462  14.457434
N       6.0  2.833333  ...  1.00  1.00    6.0  67.968567   5.509326
P       9.0  2.444444  ...  0.88  1.33    9.0  41.705744  10.047647
Q       8.0  2.625000  ...  1.00  1.00    8.0  42.915990  16.797673
R       8.0  2.500000  ...  1.00  1.13    8.0  41.542997   6.080841


           min        25%        50%        75%        max
mfr
A    54.850917  54.850917  54.850917  54.850917  54.850917
G    19.823573  27.963172  36.181877  39.587829  51.592193
K    29.924285  34.478442  40.560159  50.013484  93.704912
N    59.363993  65.459333  68.319429  71.702084  74.472949
P    28.025765  35.252444  40.917047  52.076897  53.371007
Q    18.042851  30.955582  47.419974  53.310322  63.005645
R    34.139765  36.448858  41.721976  45.528205  49.787445

[7 rows x 104 columns]

In [22]:
mfrg['name'].last()

mfr
A                      Maypo
G        Wheaties Honey Gold
K                  Special K
N    Strawberry Fruit Wheats
P      Post Nat. Raisin Bran
Q             Quaker Oatmeal
R                 Wheat Chex
Name: name, dtype: object

In [23]:
mfrg['name'].min()

mfr
A                      Maypo
G    Apple Cinnamon Cheerios
K                   All-Bran
N                  100% Bran
P                Bran Flakes
Q          100% Natural Bran
R             Almond Delight
Name: name, dtype: object

In [24]:
mfrg['name'].mean()

TypeError: Could not convert Maypo to numeric

In [25]:
mfrg.std()

,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
mfr,,,,,,,,,,,,,
A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
G,10.371873,1.129111,0.581087,44.021345,1.241421,3.347804,3.872704,45.682060,26.343756,0.833550,0.132446,0.240906,8.946704
K,22.218818,1.070628,0.838783,84.132988,3.193991,4.465060,4.500768,91.982448,25.826267,0.775107,0.154830,0.209778,14.457434
N,10.327956,0.752773,0.408248,54.931776,3.098387,5.865151,2.857738,91.829552,12.909944,0.816497,0.069402,0.272721,5.509326
P,10.540926,0.881917,1.054093,55.157602,2.333333,1.922094,4.576510,83.470720,0.000000,0.881917,0.129433,0.317101,10.047647
Q,29.277002,1.597990,1.581139,99.498744,0.998481,4.810702,5.092011,43.378525,13.363062,0.744024,0.231455,0.200637,16.797673
R,22.677868,1.069045,1.281740,56.690734,1.552648,3.248626,3.563205,66.387929,0.000000,1.069045,0.000000,0.180114,6.080841

In [28]:
cereal

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6,280,25,3,1.0,0.33,68.402973
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8,135,0,3,1.0,1.00,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5,320,25,3,1.0,0.33,59.425505
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0,330,25,3,1.0,0.50,93.704912
4,Almond Delight,R,C,110,2,2,200,1.0,14.0,8,-1,25,3,1.0,0.75,34.384843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,Triples,G,C,110,2,1,250,0.0,21.0,3,60,25,3,1.0,0.75,39.106174
73,Trix,G,C,110,1,1,140,0.0,13.0,12,25,25,2,1.0,1.00,27.753301
74,Wheat Chex,R,C,100,3,1,230,3.0,17.0,3,115,25,1,1.0,0.67,49.787445
75,Wheaties,G,C,100,3,1,200,3.0,17.0,3,110,25,1,1.0,1.00,51.592193
76,Wheaties Honey Gold,G,C,110,2,1,200,1.0,16.0,8,60,25,1,1.0,0.75,36.187559

In [29]:
len(cereal)

77

In [30]:
len(mfrg)

7

In [31]:
cereal.groupby('mfr').sum()

,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
mfr,,,,,,,,,,,,,
A,100,4,1,0,0.0,16.0,3,95,25,2,1.00,1.00,54.850917
G,2450,51,30,4410,28.0,324.0,175,1875,775,47,23.08,19.25,758.688737
K,2500,61,14,4020,63.0,348.0,174,2370,800,54,24.79,18.31,1012.884634
N,520,17,1,225,24.0,96.0,11,724,50,10,5.83,4.67,407.811403
P,980,22,8,1315,25.0,119.0,79,1025,225,22,9.58,6.43,375.351697
Q,760,21,14,740,10.7,80.0,42,595,100,19,7.00,6.59,343.327919
R,920,20,10,1585,15.0,141.0,49,714,200,16,8.00,6.97,332.343977

In [32]:
len(mfrg)

7

In [36]:
cereal['mfr'].value_counts().count()

7

In [37]:
cereal['mfr'].sum()

'NQKKRGKGRPQGGGGRKKGKNKGRKKKPKPPGPPPQGPKKGQGARRKGKKKGPKQQQQKGKRKNNNKKNGGGGGRGG'

In [38]:
cereal['mfr'].nunique()

7

In [39]:
mfrg.size()

mfr
A     1
G    22
K    23
N     6
P     9
Q     8
R     8
dtype: int64

In [41]:
type(mfrg.indices)

dict

In [42]:
mfrg.indices

{'A': array([43], dtype=int64),
 'G': array([ 5,  7, 11, 12, 13, 14, 18, 22, 31, 36, 40, 42, 47, 51, 59, 69, 70,
        71, 72, 73, 75, 76], dtype=int64),
 'K': array([ 2,  3,  6, 16, 17, 19, 21, 24, 25, 26, 28, 38, 39, 46, 48, 49, 50,
        53, 58, 60, 62, 66, 67], dtype=int64),
 'N': array([ 0, 20, 63, 64, 65, 68], dtype=int64),
 'P': array([ 9, 27, 29, 30, 32, 33, 34, 37, 52], dtype=int64),
 'Q': array([ 1, 10, 35, 41, 54, 55, 56, 57], dtype=int64),
 'R': array([ 4,  8, 15, 23, 44, 45, 61, 74], dtype=int64)}

In [45]:
mfrg.indices.keys()

dict_keys(['A', 'G', 'K', 'N', 'P', 'Q', 'R'])

In [46]:
mfrg.indices.items()

dict_items([('A', array([43], dtype=int64)), ('G', array([ 5,  7, 11, 12, 13, 14, 18, 22, 31, 36, 40, 42, 47, 51, 59, 69, 70,
       71, 72, 73, 75, 76], dtype=int64)), ('K', array([ 2,  3,  6, 16, 17, 19, 21, 24, 25, 26, 28, 38, 39, 46, 48, 49, 50,
       53, 58, 60, 62, 66, 67], dtype=int64)), ('N', array([ 0, 20, 63, 64, 65, 68], dtype=int64)), ('P', array([ 9, 27, 29, 30, 32, 33, 34, 37, 52], dtype=int64)), ('Q', array([ 1, 10, 35, 41, 54, 55, 56, 57], dtype=int64)), ('R', array([ 4,  8, 15, 23, 44, 45, 61, 74], dtype=int64))])

In [43]:
cereal.iloc[63]

name        Shredded Wheat
mfr                      N
type                     C
calories                80
protein                  2
fat                      0
sodium                   0
fiber                  3.0
carbo                 16.0
sugars                   0
potass                  95
vitamins                 0
shelf                    1
weight                0.83
cups                   1.0
rating           68.235885
Name: 63, dtype: object

In [44]:
mfrg.groups

{'A': [43], 'G': [5, 7, 11, 12, 13, 14, 18, 22, 31, 36, 40, 42, 47, 51, 59, 69, 70, 71, 72, 73, 75, 76], 'K': [2, 3, 6, 16, 17, 19, 21, 24, 25, 26, 28, 38, 39, 46, 48, 49, 50, 53, 58, 60, 62, 66, 67], 'N': [0, 20, 63, 64, 65, 68], 'P': [9, 27, 29, 30, 32, 33, 34, 37, 52], 'Q': [1, 10, 35, 41, 54, 55, 56, 57], 'R': [4, 8, 15, 23, 44, 45, 61, 74]}

In [47]:
mfrg.get_group('K')

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5,320,25,3,1.00,0.33,59.425505
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0,330,25,3,1.00,0.50,93.704912
6,Apple Jacks,K,C,110,2,0,125,1.0,11.0,14,30,25,2,1.00,1.00,33.174094
16,Corn Flakes,K,C,100,2,0,290,1.0,21.0,2,35,25,1,1.00,1.00,45.863324
17,Corn Pops,K,C,110,1,0,90,1.0,13.0,12,20,25,2,1.00,1.00,35.782791
19,Cracklin' Oat Bran,K,C,110,3,3,140,4.0,10.0,7,160,25,3,1.00,0.50,40.448772
21,Crispix,K,C,110,2,0,220,1.0,21.0,3,30,25,3,1.00,1.00,46.895644
24,Froot Loops,K,C,110,2,1,125,1.0,11.0,13,30,25,2,1.00,1.00,32.207582
25,Frosted Flakes,K,C,110,1,0,200,1.0,14.0,11,25,25,1,1.00,0.75,31.435973
26,Frosted Mini-Wheats,K,C,100,3,0,0,3.0,14.0,7,100,25,2,1.00,0.80,58.345141
28,Fruitful Bran,K,C,120,3,0,240,5.0,14.0,12,190,25,3,1.33,0.67,41.015492
38,Just Right Crunchy Nuggets,K,C,110,2,1,170,1.0,17.0,6,60,100,3,1.00,1.00,36.523683
39,Just Right Fruit & Nut,K,C,140,3,1,170,2.0,20.0,9,95,100,3,1.30,0.75,36.471512
46,Mueslix Crispy Blend,K,C,160,3,2,150,3.0,17.0,13,160,25,3,1.50,0.67,30.313351
48,Nut&Honey Crunch,K,C,120,2,1,190,0.0,15.0,9,40,25,2,1.00,0.67,29.924285
49,Nutri-Grain Almond-Raisin,K,C,140,3,2,220,3.0,21.0,7,130,25,3,1.33,0.67,40.692320
50,Nutri-grain Wheat,K,C,90,3,0,170,3.0,18.0,2,90,25,3,1.00,1.00,59.642837
53,Product 19,K,C,100,3,0,320,1.0,20.0,3,45,100,3,1.00,1.00,41.503540
58,Raisin Bran,K,C,120,3,1,210,5.0,14.0,12,240,25,2,1.33,0.75,39.259197
60,Raisin Squares,K,C,90,2,0,0,2.0,15.0,6,110,25,3,1.00,0.50,55.333142
62,Rice Krispies,K,C,110,2,0,290,0.0,22.0,3,35,25,1,1.00,1.00,40.560159
66,Smacks,K,C,110,2,1,70,1.0,9.0,15,40,25,2,1.00,0.75,31.230054
67,Special K,K,C,110,6,0,230,1.0,16.0,3,55,25,1,1.00,1.00,53.131324

In [48]:
k = mfrg.get_group('K')

In [52]:
k.loc[2,'fat'] = 9999

C:\Users\AiFTW\.conda\envs\env_2\lib\site-packages\pandas\core\indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [53]:
k

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
2,All-Bran,K,C,70,4,9999,260,9.0,7.0,5,320,25,3,1.00,0.33,59.425505
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0,330,25,3,1.00,0.50,93.704912
6,Apple Jacks,K,C,110,2,0,125,1.0,11.0,14,30,25,2,1.00,1.00,33.174094
16,Corn Flakes,K,C,100,2,0,290,1.0,21.0,2,35,25,1,1.00,1.00,45.863324
17,Corn Pops,K,C,110,1,0,90,1.0,13.0,12,20,25,2,1.00,1.00,35.782791
19,Cracklin' Oat Bran,K,C,110,3,3,140,4.0,10.0,7,160,25,3,1.00,0.50,40.448772
21,Crispix,K,C,110,2,0,220,1.0,21.0,3,30,25,3,1.00,1.00,46.895644
24,Froot Loops,K,C,110,2,1,125,1.0,11.0,13,30,25,2,1.00,1.00,32.207582
25,Frosted Flakes,K,C,110,1,0,200,1.0,14.0,11,25,25,1,1.00,0.75,31.435973
26,Frosted Mini-Wheats,K,C,100,3,0,0,3.0,14.0,7,100,25,2,1.00,0.80,58.345141
28,Fruitful Bran,K,C,120,3,0,240,5.0,14.0,12,190,25,3,1.33,0.67,41.015492
38,Just Right Crunchy Nuggets,K,C,110,2,1,170,1.0,17.0,6,60,100,3,1.00,1.00,36.523683
39,Just Right Fruit & Nut,K,C,140,3,1,170,2.0,20.0,9,95,100,3,1.30,0.75,36.471512
46,Mueslix Crispy Blend,K,C,160,3,2,150,3.0,17.0,13,160,25,3,1.50,0.67,30.313351
48,Nut&Honey Crunch,K,C,120,2,1,190,0.0,15.0,9,40,25,2,1.00,0.67,29.924285
49,Nutri-Grain Almond-Raisin,K,C,140,3,2,220,3.0,21.0,7,130,25,3,1.33,0.67,40.692320
50,Nutri-grain Wheat,K,C,90,3,0,170,3.0,18.0,2,90,25,3,1.00,1.00,59.642837
53,Product 19,K,C,100,3,0,320,1.0,20.0,3,45,100,3,1.00,1.00,41.503540
58,Raisin Bran,K,C,120,3,1,210,5.0,14.0,12,240,25,2,1.33,0.75,39.259197
60,Raisin Squares,K,C,90,2,0,0,2.0,15.0,6,110,25,3,1.00,0.50,55.333142
62,Rice Krispies,K,C,110,2,0,290,0.0,22.0,3,35,25,1,1.00,1.00,40.560159
66,Smacks,K,C,110,2,1,70,1.0,9.0,15,40,25,2,1.00,0.75,31.230054
67,Special K,K,C,110,6,0,230,1.0,16.0,3,55,25,1,1.00,1.00,53.131324

In [54]:
cereal

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6,280,25,3,1.0,0.33,68.402973
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8,135,0,3,1.0,1.00,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5,320,25,3,1.0,0.33,59.425505
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0,330,25,3,1.0,0.50,93.704912
4,Almond Delight,R,C,110,2,2,200,1.0,14.0,8,-1,25,3,1.0,0.75,34.384843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,Triples,G,C,110,2,1,250,0.0,21.0,3,60,25,3,1.0,0.75,39.106174
73,Trix,G,C,110,1,1,140,0.0,13.0,12,25,25,2,1.0,1.00,27.753301
74,Wheat Chex,R,C,100,3,1,230,3.0,17.0,3,115,25,1,1.0,0.67,49.787445
75,Wheaties,G,C,100,3,1,200,3.0,17.0,3,110,25,1,1.0,1.00,51.592193
76,Wheaties Honey Gold,G,C,110,2,1,200,1.0,16.0,8,60,25,1,1.0,0.75,36.187559